const { sequelize } = require('../models')
const { ottPlatform, Country } = sequelize.models

const getPlatforms = async (platformName) => {
  const platform = await ottPlatform.findOne({ where: { platformName } })
  if (!platform) throw new Error(`Platform '${platformName}' not found`)
  return platform.ottPlatformIndex
}

const getCountryIndex = async (countryCode) => {
  const country = await Country.findOne({ where: { countryCode } })
  if (!country) throw new Error('country not found')
  return country.countryIndex
}

const ottPlanData = async () => {
  const now = new Date()
  const ottPlanData = [
    {
      planName: 'Youtube 개인(인도네시아)',
      // planName: 'YoutubePersonalM',
      price: 59000,
      limit: 1,
      planType: 'monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Youtube'),
      countryIndex: await getCountryIndex('IDR'),
    },
    {
      planName: 'Youtube 개인(필리핀)',
      // planName: 'YoutubePersonalM',
      price: 159,
      limit: 1,
      planType: 'monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Youtube'),
      countryIndex: await getCountryIndex('PHP'),
    },
    {
      planName: 'Youtube 개인(튀르키예)',
      // planName: 'YoutubePersonalM',
      price: 29.99,
      limit: 1,
      planType: 'monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Youtube'),
      countryIndex: await getCountryIndex('TRY'),
    },
    {
      planName: 'Youtube 개인(아르헨티나)',
      // planName: 'YoutubePersonalM',
      price: 389,
      limit: 1,
      planType: 'monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Youtube'),
      countryIndex: await getCountryIndex('ARS'),
    },
    {
      planName: 'Youtube 개인(인도)',
      // planName: 'YoutubePersonalM',
      price: 129,
      limit: 1,
      planType: 'monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Youtube'),
      countryIndex: await getCountryIndex('INR'),
    },
    {
      planName: 'Youtube 개인(대한민국)',
      price: 10450,
      limit: 1,
      planType: 'monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Youtube'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'Youtube 패밀리(인도네시아)',
      // planName: 'YoutubeFamilyM',
      price: 99000,
      limit: 4,
      planType: 'monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Youtube'),
      countryIndex: await getCountryIndex('IDR'),
    },

    {
      planName: 'Youtube 패밀리(필리핀)',
      // planName: 'YoutubeFamilyM',
      price: 239,
      limit: 4,
      planType: 'monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Youtube'),
      countryIndex: await getCountryIndex('PHP'),
    },

    {
      // planName: 'YoutubeFamilyM',
      planName: 'Youtube 패밀리(튀르키예)',
      price: 59.99,
      limit: 4,
      planType: 'monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Youtube'),
      countryIndex: await getCountryIndex('TRY'),
    },

    {
      planName: 'Youtube 패밀리(아르헨티나)',
      // planName: 'YoutubeFamilyM',
      price: 699,
      limit: 4,
      planType: 'monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Youtube'),
      countryIndex: await getCountryIndex('ARS'),
    },

    {
      planName: 'Youtube 패밀리(인도)',
      // planName: 'YoutubeFamilyM',
      price: 189,
      limit: 4,
      planType: 'monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Youtube'),
      countryIndex: await getCountryIndex('INR'),
    },
    {
      planName: 'Netflix Ad Basic M',
      price: 5500,
      limit: 1,
      planType: 'Monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Netflix'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'Netflix Basic M',
      price: 9500,
      limit: 1,
      planType: 'Monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Netflix'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'Netflix Standard M',
      price: 13500,
      limit: 2,
      planType: 'Monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Netflix'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'Netflix Premium M',
      price: 17000,
      limit: 4,
      planType: 'Monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Netflix'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'Disney Public M',
      price: 9900,
      limit: 4,
      planType: 'Monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('DisneyPlus'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'Disney Public Y',
      price: 99000,
      limit: 4,
      planType: 'Yearly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('DisneyPlus'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'Watcha Basic M',
      price: 7900,
      limit: 1,
      planType: 'Monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Watcha'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'Watcha Premium M',
      price: 12900,
      limit: 4,
      planType: 'Monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Watcha'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'Wavve Basic M',
      price: 7900,
      limit: 1,
      planType: 'Mothly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Wavve'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'Wavve Standard M',
      price: 10900,
      limit: 2,
      planType: 'Mothly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Wavve'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'Wavve Premium M',
      price: 13900,
      limit: 4,
      planType: 'Mothly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Wavve'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'Wavve Basic Y',
      price: 79000,
      limit: 1,
      planType: 'Yearly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Wavve'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'Wavve Standard Y',
      price: 109000,
      limit: 2,
      planType: 'Yearly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Wavve'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'Wavve Basic Y',
      price: 139000,
      limit: 4,
      planType: 'Yearly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Wavve'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'Tving Basic M',
      price: 7900,
      limit: 1,
      planType: 'Mothly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Tving'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'Tving Standard M',
      price: 10900,
      limit: 2,
      planType: 'Mothly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Tving'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'Tving Premium M',
      price: 13900,
      limit: 4,
      planType: 'Mothly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Tving'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'Tving Basic Y',
      price: 71000,
      limit: 0,
      planType: 'Yearly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Tving'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'Tving Standard Y',
      price: 98000,
      limit: 2,
      planType: 'Yearly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Tving'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'Tving Premium Y',
      price: 125000,
      limit: 4,
      planType: 'Yearly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Tving'),
      countryIndex: await getCountryIndex('KRW'),
    },
  ]
  return ottPlanData
}

module.exports = ottPlanData

// Data add Form
//   {
//     planName: '',
//     price: 0,
//     limit: 0,
//     planType : '',
//     createdAt: now,
//     updatedAt: now,
//     ottPlatformIndex: await getPlatforms(''),
//     countryIndex: await getCountryIndex(''),
//   },
