const { sequelize } = require('../models')
const { ottPlatforms, Country } = sequelize.models

const getPlatforms = async (platformName) => {
  const platform = await ottPlatforms.findOne({ where: { platformName } })
  if (!platform) throw new Error('platform not found')
  return platform.ottPlatformIndex
}

const getCountryIndex = async (countryCode) => {
  const country = await Country.findOne({ where: { countryCode } })
  if (!country) throw new Error('country not found')
  return country.countryIndex
}

const ottPlanData = async () => {
  const now = new Date()
  const ottPlanData = [
    {
      planName: 'YoutubePersonalM',
      price: 59000,
      limit: 1,
      planType: 'monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Youtube'),
      countryIndex: await getCountryIndex('IDR'),
    },
    {
      planName: 'YoutubePersonalM',
      price: 159,
      limit: 1,
      planType: 'monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Youtube'),
      countryIndex: await getCountryIndex('PHP'),
    },
    {
      planName: 'YoutubePersonalM',
      price: 29.99,
      limit: 1,
      planType: 'monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Youtube'),
      countryIndex: await getCountryIndex('TRY'),
    },
    {
      planName: 'YoutubePersonalM',
      price: 389,
      limit: 1,
      planType: 'monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Youtube'),
      countryIndex: await getCountryIndex('ARS'),
    },
    {
      planName: 'YoutubePersonalM',
      price: 129,
      limit: 1,
      planType: 'monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Youtube'),
      countryIndex: await getCountryIndex('INR'),
    },
    {
      planName: 'YoutubePersonalM',
      price: 10450,
      limit: 1,
      planType: 'monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Youtube'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'YoutubeFamilyM',
      price: 99000,
      limit: 4,
      planType: 'monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Youtube'),
      countryIndex: await getCountryIndex('IDR'),
    },

    {
      planName: 'YoutubeFamilyM',
      price: 239,
      limit: 4,
      planType: 'monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Youtube'),
      countryIndex: await getCountryIndex('PHP'),
    },

    {
      planName: 'YoutubeFamilyM',
      price: 59.99,
      limit: 4,
      planType: 'monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Youtube'),
      countryIndex: await getCountryIndex('TRY'),
    },

    {
      planName: 'YoutubeFamilyM',
      price: 699,
      limit: 4,
      planType: 'monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Youtube'),
      countryIndex: await getCountryIndex('ARS'),
    },

    {
      planName: 'YoutubeFamilyM',
      price: 189,
      limit: 4,
      planType: 'monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Youtube'),
      countryIndex: await getCountryIndex('INR'),
    },
    {
      planName: 'NetflixAdBasicM',
      price: 5500,
      limit: 1,
      planType: 'Monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Netflix'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'NetflixBasicM',
      price: 9500,
      limit: 1,
      planType: 'Monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Netflix'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'NetflixStandardM',
      price: 13500,
      limit: 2,
      planType: 'Monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Netflix'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'NetflixPremiumM',
      price: 17000,
      limit: 4,
      planType: 'Monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Netflix'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'DisneyPublicM',
      price: 9900,
      limit: 4,
      planType: 'Monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('DisneyPlus'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'DisneyPublicY',
      price: 99000,
      limit: 4,
      planType: 'Yearly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('DisneyPlus'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'WatchaBasicM',
      price: 7900,
      limit: 1,
      planType: 'Monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Watcha'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'WatchaPremiumM',
      price: 12900,
      limit: 4,
      planType: 'Monthly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Watcha'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'WavveBasicM',
      price: 7900,
      limit: 1,
      planType: 'Mothly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Wavve'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'WavveStandardM',
      price: 10900,
      limit: 2,
      planType: 'Mothly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Wavve'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'WavvePremiumM',
      price: 13900,
      limit: 4,
      planType: 'Mothly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Wavve'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'WavveBasicY',
      price: 79000,
      limit: 1,
      planType: 'Yearly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Wavve'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'WavveStandardY',
      price: 109000,
      limit: 2,
      planType: 'Yearly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Wavve'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'WavveBasicY',
      price: 139000,
      limit: 4,
      planType: 'Yearly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Wavve'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'TvingBasicM',
      price: 7900,
      limit: 1,
      planType: 'Mothly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Tving'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'TvingStandardM',
      price: 10900,
      limit: 2,
      planType: 'Mothly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Tving'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'TvingPremiumM',
      price: 13900,
      limit: 4,
      planType: 'Mothly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Tving'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'TvingBasicY',
      price: 71000,
      limit: 0,
      planType: 'Yearly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Tving'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'TvingStandardY',
      price: 98000,
      limit: 2,
      planType: 'Yearly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Tving'),
      countryIndex: await getCountryIndex('KRW'),
    },
    {
      planName: 'TvingPremiumY',
      price: 125000,
      limit: 4,
      planType: 'Yearly',
      createdAt: now,
      updatedAt: now,
      ottPlatformIndex: await getPlatforms('Tving'),
      countryIndex: await getCountryIndex('KRW'),
    },
  ]
  return ottPlanData
}

module.exports = ottPlanData()

// Data add Form
//   {
//     planName: '',
//     price: 0,
//     limit: 0,
//     planType : '',
//     createdAt: now,
//     updatedAt: now,
//     ottPlatformIndex: await getPlatforms(''),
//     countryIndex: await getCountryIndex(''),
//   },
