name: Auto-update

on:
  schedule:
    - cron: '0 0 * * *' # 매일 자정마다 실행

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update code
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git pull
        git add .
        git commit -m "Auto-update $(date +%Y-%m-%d)"
        git push
